CREATE DATABASE IF NOT EXISTS MmtTechTest;	
USE MmtTechTest;

CREATE TABLE IF NOT EXISTS Categories(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS Products(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(40),
  sku BIGINT,
  description VARCHAR(150),
  price DECIMAL(13, 2),
  category TINYINT
);
